version: '3'

# ibcs / aYgYVB@r(raGDF1dU5

services:
  php:
    build:
      context: ./
      dockerfile: ./docker_utils/php.Dockerfile
    working_dir: /var/www/html
    networks:
      - backend
      - frontend
    volumes:
      - ./:/var/www/html
      - ./docker_utils/httpd.conf:/usr/local/apache2/conf/httpd.conf
    links: 
      - mysql:db
    depends_on:
      - mysql
    ports:
      - 80:80
  
  react:
    image: node:13.12.0-alpine3.11
    working_dir: /home/node/app
    volumes:
      - ./client:/home/node/app
    stdin_open: true
    ports:
      - 8080:3000
    command: "npm run start"
    networks:
      - frontend
      - backend

  mysql:
    image: mysql:5.7
    volumes:
      - ./data:/var/lib/mysql
    env_file:
      - .env
    environment:
      - MYSQL_DATABASE=$DB_DATABASE
      - MYSQL_USER=$DB_USER
      - MYSQL_PASSWORD=$DB_PASS
      - MYSQL_ROOT_PASSWORD=$DB_PASS
    command: --default-authentication-plugin=mysql_native_password

networks:
  backend:
    internal: true
  frontend: