version: '3'

# ibcs / aYgYVB@r(raGDF1dU5

services:
  httpd:
    image: httpd:2.4.43-alpine
    volumes:
      - .:/usr/local/apache2/htdocs/
      - ./httpd.conf:/usr/local/apache2/conf/httpd.conf
      # - .:/usr/local/apache2/htdocs/
    ports:
      - 80:80

  node:
    image: node:13.12.0-alpine3.11
    working_dir: /home/node/app
    volumes:
      - ./server:/home/node/app
    stdin_open: true
    ports:
      - 3000:3000
    command: "npm run start"
    networks:
      - frontend
      - backend
  
  react:
    image: node:13.12.0-alpine3.11
    working_dir: /home/node/app
    volumes:
      - ./client:/home/node/app
    stdin_open: true
    ports:
      - 8080:3000
    command: "npm run start"
    networks:
      - frontend
      - backend

  # mysql:
  #   image: mysql:5.7
  #   volumes:
  #     - ./data:/var/lib/mysql
  #   environment:
  #     - MYSQL_DATABASE=wp_ibcs
  #     - MYSQL_USER=root
  #     - MYSQL_PASSWORD=root
  #     - MYSQL_ROOT_PASSWORD=root
  #   command: --default-authentication-plugin=mysql_native_password

networks:
  backend:
    internal: true
  frontend: